### ISSUE TITLE
why not use the ppa

### ISSUE THREAD

**Issue by mskyaxl** [n3ddu8/neovim-for-debian#1]
Hi!, why aren't you using this ppa https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable to get the latest version on Ubuntu?

I am in the search for a way to install a prebuild package on debian. I did not find yet an apt repo for it..

**Comment by n3ddu8** [comment]
Hi, thanks for the info, I'm primarily using this a a good use case to play with GitHub actions - I've not committed the workflow yet but the idea is that eventually it will automatically create a new release each time there is a new release of Neovim. This is also the latest stable version of Neovim whereas it looks like the PPA you shared is the latest unstable build. I've not yet looked at creating PPAs with this method. TBH, outside of work I run Fedora Silverblue and either use the Neovim flatpak or run it in a container so working with PPA's isn't really something I'm looking to learn about.

**Comment by mskyaxl** [comment]
https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable there is also a stable version :)
